### PR TITLE
Fix label alignment

### PR DESCRIPTION
**Pull request by fniephaus**

### CODE REVIEW

**Comment by marceltaeumel** [comment]
This should not be necessary since text morphs have their correct bounds directly after creation. Try out `'Hello' asText asMorph width` or `'Hello World!' asText asMorph width`.

**Comment by fniephaus** [comment]
Your examples WAI, maybe there's a problem with rotated morphs (height <-> width)?

**Comment by marceltaeumel** [comment]
Does this work for you?

```Smalltalk
text := 'Hello, World!' asText asMorph.

shell := TransformMorph new.

shell addMorph: text.
shell angle: Float pi/2.
shell extent: text height @ text width.	
	
text left: text left - text width.
"text left: text width negated".

shell openInHand.
```

**Comment by fniephaus** [comment]
I guess it does:
image

**Comment by marceltaeumel** [comment]
Which version of Widgets do you have? Widgets-mt.534?

**Pull request closed without merging**
